name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: maven
      - name: Get Project Version
        run: echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Copy JAR to Target Directory
        run: mkdir staging && cp target/*.jar staging
      - name: Save JAR as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: BukkitTimer-${{ env.RELEASE_VERSION }}
          path: staging/BukkitTimer-${{ env.RELEASE_VERSION }}.jar
